AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  MyBucketName:
    Description: "create public s3 bucket where anyone can see."
    Type: String
    MinLength: 10
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z0-9]*$
Resources:
  MyS3Bucket:
    Description: "S3 bucket"
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref MyBucketName
  MyS3BucketPolicy:
    Description: "Policy of bucket rules anyone can watch inside of the bucket"
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
          # reading object
          - Action:
            - 's3:GetObject'
            Effect: Allow
            # to anyone
            Principal: '*'
            # for my bucket
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref MyBucketName
                - '/*'
Outputs:
  CreatedS3:
    Value: !Ref MyS3Bucket
